### ISSUE TITLE
Support for newrelic >=10.0.0 

### ISSUE THREAD

**Issue by darkleaf** [newrelic/node-newrelic-koa#153]
Newrelic >= 10.0.0 is not supported by newrelic/koa.

```
    "@newrelic/koa": "=7.2.0",
    "newrelic": "=10.0.0",
```

node:16.11.0

```
nodejs-nodejs-1        | 
nodejs-nodejs-1        | > example@1.0.0 start
nodejs-nodejs-1        | > node ./index.js
nodejs-nodejs-1        | 
nodejs-nodejs-1        | {"v":0,"level":30,"name":"newrelic","hostname":"2242b93589b3","pid":20,"time":"2023-06-28T11:03:45.736Z","msg":"Unable to find configuration file. If a configuration file is desired (common for non-containerized environments), a base configuration file can be copied from /app/node_modules/newrelic/newrelic.js and renamed to \"newrelic.js\" in the directory from which you will start your application. Attempting to start agent using environment variables."}
nodejs-nodejs-1        | {"v":0,"level":30,"name":"newrelic","hostname":"2242b93589b3","pid":20,"time":"2023-06-28T11:03:45.740Z","msg":"Using New Relic for Node.js. Agent version: 10.0.0; Node version: v16.11.0."}
nodejs-nodejs-1        | {"v":0,"level":30,"name":"newrelic","hostname":"2242b93589b3","pid":20,"time":"2023-06-28T11:03:45.873Z","msg":"Using LegacyContextManager"}
nodejs-nodejs-1        | {"v":0,"level":30,"name":"newrelic","hostname":"2242b93589b3","pid":20,"time":"2023-06-28T11:03:45.880Z","msg":"Adding destroy hook to clean up unresolved promises.","component":"async_hooks"}
nodejs-nodejs-1        | {"v":0,"level":30,"name":"newrelic","hostname":"2242b93589b3","pid":20,"time":"2023-06-28T11:03:45.926Z","msg":"Agent state changed from stopped to starting."}
nodejs-nodejs-1        | {"v":0,"level":30,"name":"newrelic","hostname":"2242b93589b3","pid":20,"time":"2023-06-28T11:03:45.957Z","msg":"Starting New Relic for Node.js connection process."}
nodejs-nodejs-1        | {"v":0,"level":30,"name":"newrelic","hostname":"2242b93589b3","pid":20,"time":"2023-06-28T11:03:45.957Z","msg":"Agent state changed from starting to connecting."}
nodejs-terminator-1    | 127.0.0.1 - - [28/Jun/2023:11:03:46 +0000] "GET / HTTP/1.1" 200 615 "-" "curl/7.74.0" "-"
nodejs-nodejs-1        | {"v":0,"level":30,"name":"newrelic","hostname":"2242b93589b3","pid":20,"time":"2023-06-28T11:03:47.156Z","msg":"Agent state changed from connecting to connected."}
nodejs-nodejs-1        | {"v":0,"level":30,"name":"newrelic","hostname":"2242b93589b3","pid":20,"time":"2023-06-28T11:03:47.157Z","msg":"Connected to collector.eu01.nr-data.net:443 with agent run ID XXXXXXX.","component":"collector_api"}
nodejs-nodejs-1        | {"v":0,"level":30,"name":"newrelic","hostname":"2242b93589b3","pid":20,"time":"2023-06-28T11:03:47.157Z","msg":"Reporting to: https://rpm.eu.newrelic.com/accounts/XXXXX/applications/XXXXXX","component":"collector_api"}
nodejs-nodejs-1        | {"v":0,"level":30,"name":"newrelic","hostname":"2242b93589b3","pid":20,"time":"2023-06-28T11:03:47.158Z","msg":"Valid event_harvest_config received. Updating harvest cycles. {\"report_period_ms\":5000,\"harvest_limits\":{\"error_event_data\":8,\"log_event_data\":833,\"analytic_event_data\":833,\"custom_event_data\":250}}"}
nodejs-nodejs-1        | {"v":0,"level":30,"name":"newrelic","hostname":"2242b93589b3","pid":20,"time":"2023-06-28T11:03:47.161Z","msg":"Agent state changed from connected to started."}
nodejs-nodejs-1        | {"v":0,"level":30,"name":"newrelic","hostname":"2242b93589b3","pid":20,"time":"2023-06-28T11:03:48.162Z","msg":"Starting initial 1000ms harvest."}
nodejs-nodejs-1        | /app/node_modules/newrelic/lib/transaction/tracer/index.js:211
nodejs-nodejs-1        |       throw err // Re-throwing application error, this is not an agent error.
nodejs-nodejs-1        |       ^
nodejs-nodejs-1        | 
nodejs-nodejs-1        | TypeError: Cannot redefine property: _body
nodejs-nodejs-1        |     at Function.defineProperty (<anonymous>)
nodejs-nodejs-1        |     at Application.wrapCreateContext (/app/node_modules/@newrelic/koa/lib/instrumentation.js:77:10)
nodejs-nodejs-1        |     at Object.applyTrap [as apply] (/app/node_modules/newrelic/lib/shim/shim.js:690:29)
nodejs-nodejs-1        |     at Server.handleRequest (/app/node_modules/koa/lib/application.js:155:24)
nodejs-nodejs-1        |     at Server.emit (node:events:390:28)
nodejs-nodejs-1        |     at LegacyContextManager.runInContext (/app/node_modules/newrelic/lib/context-manager/legacy-context-manager.js:59:23)
nodejs-nodejs-1        |     at Server.wrapped (/app/node_modules/newrelic/lib/transaction/tracer/index.js:203:37)
nodejs-nodejs-1        |     at Server.wrappedHandler (/app/node_modules/newrelic/lib/instrumentation/core/http.js:193:47)
nodejs-nodejs-1        |     at LegacyContextManager.runInContext (/app/node_modules/newrelic/lib/context-manager/legacy-context-manager.js:59:23)
nodejs-nodejs-1        |     at Server.wrapped (/app/node_modules/newrelic/lib/transaction/tracer/index.js:203:37)
nodejs-nodejs-1 exited with code 1
```

**Comment by bizob2828** [comment]
Hi @darkleaf, due to new functionality in 10.0.0 of the Node.js agent(newrelic), this package will no longer function as a standalone. In fact we have a change queued up to no longer allow this. It's worth noting this package is already bundled in the agent and you don't need to use this as a standalone. Let us know if you have any questions but I'm closing this issue.

**Comment by darkleaf** [comment]
Thanks!
Could you please add some info into Readme?

**Comment by bizob2828** [comment]
@darkleaf ah yea, it looks like it was forgotten when we removed the capability.  It's worth noting we're holding off on releasing this until later this quarter when we also add Node 20 and drop Node 14.
